# Generated by Django 5.1.4 on 2025-02-17 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_busdetails_fleetnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_route', to='main.routedetails'),
        ),
        migrations.CreateModel(
            name='RouteChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_route', models.CharField(max_length=100)),
                ('requested_route', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_change', to='main.driverconductor')),
            ],
        ),
        migrations.DeleteModel(
            name='RouteBus',
        ),
    ]
