# Generated by Django 5.1.4 on 2025-02-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_busdetails_route_routechangerequest_delete_routebus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routechangerequest',
            name='current_route',
        ),
    ]
