# Generated by Django 5.1.4 on 2025-03-08 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_routechangerequest_current_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_driver', to='main.driverconductor'),
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_route', to='main.routedetails'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_payment', to='main.busdetails'),
        ),
    ]
